/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_annimon_minizipandroid_MinizipWrapper */

#ifndef _Included_com_annimon_minizipandroid_MinizipWrapper
#define _Included_com_annimon_minizipandroid_MinizipWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_annimon_minizipandroid_MinizipWrapper
 * Method:    createZip
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_annimon_minizipandroid_MinizipWrapper_createZip
  (JNIEnv *, jobject, jstring, jstring, jstring);

/*
 * Class:     com_annimon_minizipandroid_MinizipWrapper
 * Method:    extractZip
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_annimon_minizipandroid_MinizipWrapper_extractZip
  (JNIEnv *, jobject, jstring, jstring, jstring);

/*
 * Class:     com_annimon_minizipandroid_MinizipWrapper
 * Method:    getFilenameInZip
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_annimon_minizipandroid_MinizipWrapper_getFilenameInZip
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
